apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-deployment
  labels:
    app: commandservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commandservice
  template:
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
      - name: commandservice
        image: kbourzayq/commandservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: commands-service
spec:
  selector:
    app: commandservice
  ports:
  - port: 80
    targetPort: 80
