apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-deployment
  labels:
    app: platformservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
      - name: platformservice
        image: kbourzayq/platformservice:latest
